---
- name: output volume name
  debug:
    msg: "{{ volume_name }}"

- name: Gather information about volume
  ec2_vol_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ volume_name }}"
  register: volume_info

- name: set volume fact
  set_fact:
    volume_id: "{{ volume_info.volumes[0].id }}"
    volume_status: "{{ volume_info.volumes[0].attachment_set.instance_id != instance_data.content }}"

- name: Async script to check ebs volume status
  template:
    src: check_ebs_volume.sh.j2
    dest: /root/check_ebs_volume.sh
  when: volume_status

- name: wait for ebs to be released and continue with play
  command: "sh /root/check_ebs_volume.sh"
  async: 600
  poll: 10
  register: check_volume_state
  when: volume_status

- name: check volume async task
  async_status:
    jid: "{{ check_volume_state.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 10
  when: volume_status

- name: attach ebs volume
  ec2_vol:
    instance: "{{ instance_data.content }}"
    name: "{{ volume_name }}"
    device_name: "{{ device_name }}"
    region: "{{ region }}"
