---
# tasks file for hmpps-solr-bootstrap

- name: get instance_id
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    return_content: yes
  register: instance_data

- name: Gather information about instance
  uri:
    url: http://169.254.169.254/latest/dynamic/instance-identity/document
    return_content: yes
  register: instance_info

- name: set instance_facts
  set_fact:
    instance_az: "{{ instance_info.json.availabilityZone }}"
    node_ip_address: "{{ ansible_default_ipv4.address }}"

- name: Reconfigure our system time sync
  include: configure_time.yml

- name: Reconfigure our logging services so we audit correctly
  include: configure_auditing.yml
  when:
    - manage_auditing

- name: manage storage devices
  include_tasks: manage_storage.yml
  when: manage_storage

- name: update solr config
  include_tasks: configure_solr.yml
