---
# tasks file for hmpps-solr-bootstrap
- name: Gather instance facts
  ec2_metadata_facts:
  register: instance_facts

- name: set instance facts 
  set_fact:
    instance_ip: "{{ instance_facts.ansible_facts.ansible_ec2_local_ipv4 }}"
    instance_az: "{{ instance_facts.ansible_facts.ansible_ec2_placement_availability_zone }}"
    instance_id: "{{ instance_facts.ansible_facts.ansible_ec2_instance_id }}"

- name: Reconfigure our system time sync
  include: configure_time.yml

- name: Reconfigure our logging services so we audit correctly
  include: configure_auditing.yml
  when:
    - manage_auditing

- name: manage storage devices
  include_tasks: manage_storage.yml
  when: manage_storage

- name: update solr config
  include_tasks: configure_solr.yml
