---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-role-solr
  vars:
    solr_change_default_password: false
    solr_copy_default_configsets: true
    solr_service_restart: no
    solr_use_java_version_8: false
