---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image_owner: 895523100917
    image_name: "HMPPS Solr *"
    instance_type: t2.medium
    vpc_subnet_id: subnet-043763902fc8ac91c
    instance_profile_name: "packer_solr_builder"
    instance_tags:
      destroy: true
      created_by: molecule
      Name: hmpps-solr-bootstrap
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    v: true
    sudo: true
  lint:
    name: flake8
